### ISSUE TITLE
Error importing from solps_3d_functions

### ISSUE THREAD

**Issue by TomFarley** [cherab/solps#14]
On a fresh install of the solps module (cherab-solps==1.0.0) imports from solps_3d_functions are broken in the main __init__.py:

`tfarley@freia013:~/repos/cherab/solps$ ipython
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cherab.solps                                                                                                                                                            
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bf37c7c8a685> in <module>
----> 1 import cherab.solps

~/repos/cherab/solps/cherab/solps/__init__.py in <module>
     18 # under the Licence.
     19 
---> 20 from .solps_3d_functions import SOLPSFunction3D, SOLPSVectorFunction3D
     21 from .mesh_geometry import SOLPSMesh
     22 from .solps_plasma import SOLPSSimulation

ModuleNotFoundError: No module named 'cherab.solps.solps_3d_functions'`

Similarly the unittests fail with:
`tfarley@freia013:~/repos/cherab/solps$ nosetests
E
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'cherab.solps.solps_3d_functions')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/depot/Python-3.7/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/depot/Python-3.7/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/depot/Python-3.7/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/depot/Python-3.7/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/depot/Python-3.7/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/local/depot/Python-3.7/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tfarley/repos/cherab/solps/cherab/solps/__init__.py", line 20, in <module>
    from .solps_3d_functions import SOLPSFunction3D, SOLPSVectorFunction3D
ModuleNotFoundError: No module named 'cherab.solps.solps_3d_functions'

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (errors=1)`

**Comment by jacklovell** [comment]
We traced this back to an installation issue with Raysect and Cherab Core. The user had Python 3.7 and Numpy 1.15.4 installed. `pip install raysect` pulled in the manylinux wheel for raysect 0.6.0, which was built with Numpy 1.16 and is incompatible with 1.15.4. This install appeared to succeed but was actually broken, and meant subsequent installs of cherab-core and cherab-solps failed.

The solution, for users with older Numpy, is to install raysect and cherab from source. This can be done by either passing the `--no-binary` option to pip or by cloning the raysect and cherab repos and installing from these local checkouts.
